name: Salvar arquivo csv todo dia às 12h 30min

on:
  schedule:
    - cron: "30 12 * * *"

jobs:
  save_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Instalar dependências
        run: pip install pandas schedule statsmodels meteostat 

      - name: Executar código Python
        run: python save.py
          
      # Add new files in data folder, commit along with other modified files, push
      - name: Commit e push das alterações
        run: |
          git pull origin main
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "Atualizar arquivo CSV $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
        
        
    

